// Single source of truth for published blog articles (kampaio).
//
// The blog index (/blog), the per-article cover renderer (article-og.tsx), and
// the "Keep reading" related block all read from `blogPosts` here. The publisher
// prepends one entry per publish. Moved out of blog/page.tsx so the cover system
// and recirculation can share it without a second array drifting.

export type BlogPost = {
  id: number;
  title: string;
  excerpt: string;
  category: string;
  author: string;
  date: string; // ISO YYYY-MM-DD
  readTime: string; // "9 min read"
  slug: string;
  featured?: boolean;
};

// Display label per cluster id (mirrors the /blog category filter).
export const CATEGORY_LABEL: Record<string, string> = {
  ai: 'AI & Automation',
  'ai-search': 'AI Search',
  'google-ads': 'Google Ads',
  strategy: 'Strategy',
  ppc: 'PPC',
  b2b: 'B2B',
};

export const blogPosts: BlogPost[] = [
  { id: 306, title: 'Google AI Ads: What Google Turned On in Your Account, and What to Keep vs Kill', excerpt: "Google switched AI on across your ad account: AI Max, ads in AI Overviews and AI Mode, auto-created assets. Here's exactly what each one changes, where the controls are, and our keep-kill-monitor call for every one.", category: 'ai', author: 'By Kampaio Team', date: '2026-07-14', readTime: '13 min read', slug: 'google-ai-ads' },
  { id: 305, title: 'ChatGPT for Google Ads: What It Does Well, Where It Falls Short (Honest 2026 Guide)', excerpt: "ChatGPT is a strong copilot for Google Ads copy, keywords, and reporting, but it can't see your account or make safe changes. Here's what it does well, where it fails, and the prompts that actually work.", category: 'ai', author: 'By Kampaio Team', date: '2026-07-13', readTime: '10 min read', slug: 'chatgpt-google-ads' },
  { id: 304, title: "Google Ads Optimization Score: What's a Good Score, and Should You Chase 100%?", excerpt: "Google Ads optimization score measures how many recommendations you've applied, not how well your account performs. Here's what a good score actually is, and why chasing 100% can raise your CPCs and hurt ROAS.", category: 'google-ads', author: 'By Kampaio Team', date: '2026-07-10', readTime: '10 min read', slug: 'google-ads-optimization-score' },
  { id: 303, title: 'B2B PPC Strategy: How to Scale Paid Search Without Efficiency Collapse', excerpt: 'A B2B PPC strategy built for scale, not basics: funnel-aligned structure, offline-conversion signal wiring, value-based bidding, and a clear rule for when to automate. With data from 68 practitioner discussions.', category: 'b2b', author: 'By Kampaio Team', date: '2026-07-10', readTime: '11 min read', slug: 'b2b-ppc-strategy' },
  { id: 302, title: 'Google Ads Consultant: What They Do, What They Cost, and When to Hire One', excerpt: "An honest buyer's guide to Google Ads consultants: what they actually do, real cost ranges (freelancer vs agency vs software), the hiring red flags, and how to know if you need one at all.", category: 'strategy', author: 'By Kampaio Team', date: '2026-07-07', readTime: '13 min read', slug: 'google-ads-consultant' },
  { id: 301, title: 'Performance Max Optimization: The 7-Lever Playbook (In the Right Order)', excerpt: 'A sequenced Performance Max optimization playbook: which of 7 levers to touch first, what to leave alone during learning, and the weekly cadence that beats random tweaking.', category: 'google-ads', author: 'By Kampaio Team', date: '2026-06-29', readTime: '11 min read', slug: 'performance-max-optimization' },
  { id: 300, title: 'White Label Google Ads: When to Outsource, Hire, or Use Software (A Neutral Decision Guide)', excerpt: 'A neutral decision guide for agency owners weighing white label Google Ads vs hiring in-house vs software. The real margin math, provider red flags, and when each model actually wins.', category: 'strategy', author: 'By Kampaio Team', date: '2026-06-26', readTime: '12 min read', slug: 'white-label-google-ads' },
  { id: 299, title: 'Landing Page Optimization for Google Ads (Quality Score Fix)', excerpt: 'Your landing page feeds Quality Score, which sets your Ad Rank and CPC. Here is the diagnostic chain and the ordered fix list: message match, speed, mobile, LPE flags.', category: 'google-ads', author: 'By Kampaio Team', date: '2026-06-25', readTime: '11 min read', slug: 'landing-page-optimization-for-google-ads' },
  { id: 298, title: 'Google Ads Agency vs In-House vs Software: Which Is Right for Your Budget?', excerpt: 'A neutral 3-way comparison of running Google Ads via an agency, an in-house team, or self-serve software. Real US costs, control and effort tradeoffs, and a spend-based verdict for each path.', category: 'strategy', author: 'By Kampaio Team', date: '2026-06-23', readTime: '9 min read', slug: 'google-ads-agency-vs-in-house-vs-software' },
  { id: 297, title: 'Google Ads AI Agent: What They Actually Do, Where They Break, and How to Choose (2026)', excerpt: "A Google Ads AI agent runs campaign tasks autonomously, not just suggests them. We break down what they do, where they fail, Google's own agents, and how to pick one.", category: 'ai', author: 'By Kampaio Team', date: '2026-06-23', readTime: '12 min read', slug: 'google-ads-ai-agent' },
  { id: 296, title: 'Why Is My Google Ads Account Suspended? Causes, Fixes, and How to Appeal', excerpt: "Your Google Ads account got suspended and Google's email is vague. Here are the real causes, how to find yours, and a step-by-step appeal that actually works.", category: 'google-ads', author: 'By Marcus', date: '2026-06-22', readTime: '11 min read', slug: 'why-is-my-google-ads-account-suspended' },
  { id: 295, title: 'Google Ads Optimizer Software, Compared: Do You Actually Need One?', excerpt: 'A neutral comparison of Google Ads optimizer software (Optmyzr, TheOptimizer, Google Recommendations, AI-native tools) plus a framework for deciding when an optimizer beats doing it manually.', category: 'google-ads', author: 'By Kampaio Team', date: '2026-06-22', readTime: '9 min read', slug: 'google-ads-optimizer-software-compared' },
  { id: 294, title: 'Google Shopping Feed Optimization: The Attribute-by-Attribute Build Order (2026)', excerpt: 'A setup-first guide to Google Shopping feed optimization: the attribute priority order, exact character limits, and the disapproval triggers that vendor "optimize your titles" advice skips. Built for PPC managers who own the feed.', category: 'google-ads', author: 'By Kampaio Team', date: '2026-06-21', readTime: '9 min read', slug: 'google-shopping-feed-optimization' },
  { id: 293, title: 'Google Ads AI vs Manual Bidding: How to Decide (with Real Data)', excerpt: 'AI (Smart) bidding vs manual bidding in Google Ads, decided by account stage, conversion volume, and goal. A decision matrix plus real attributed performance data, not "it depends."', category: 'ai', author: 'By Kampaio Team', date: '2026-06-20', readTime: '12 min read', slug: 'google-ads-ai-vs-manual-bidding' },
  { id: 292, title: 'Google Shopping Optimization: Diagnose First, Fix Second', excerpt: 'Most Google Shopping guides jump straight to "optimize your titles." But if your bids are wrong or your campaign structure is broken, feed tweaks won\'t save you. Here\'s a diagnostic-first framework for DTC store owners running their own campaigns.', category: 'google-ads', author: 'By Kampaio Team', date: '2026-06-19', readTime: '10 min read', slug: 'google-shopping-optimization' },
  { id: 45, title: 'B2B PPC Advertising: How to Set It Up Without Burning Your First Month\'s Budget (2026)', excerpt: 'A hands-on setup guide for B2B PPC advertising: the channels, account structure, match types, conversion tracking, and first-30-days bidding that stop a B2B campaign from bleeding budget on the wrong clicks, plus a week-by-week launch checklist and when to automate.', category: 'b2b', author: 'By Kampaio Team', date: '2026-06-18', readTime: '11 min read', slug: 'b2b-ppc-advertising' },
  { id: 44, title: 'Google Ads Optimization: The Complete Guide (2026)', excerpt: 'A diagnostic-first system for optimizing Google Ads in 2026: find your real constraint, pull the highest-leverage lever, measure the lift, and know when to leave a campaign alone. Built for operators, not checklist-followers.', category: 'google-ads', author: 'By Kampaio Team', date: '2026-06-17', readTime: '15 min read', slug: 'google-ads-optimization' },
  { id: 43, title: 'B2B PPC Lead Generation: How to Buy Pipeline, Not Just Leads (2026)', excerpt: 'Most B2B PPC advice optimizes for cheap leads. This pillar covers the quality layer: the four levers of lead quality, the CRM conversion feedback loop, channel selection by intent, and the only metric that matters, cost per closed-won, as spend scales from $10K to $100K per month.', category: 'b2b', author: 'By Kampaio Team', date: '2026-06-17', readTime: '11 min read', slug: 'b2b-ppc-lead-generation' },
  { id: 42, title: 'B2B SaaS Google Ads Campaign Structure: The Account Blueprint (2026)', excerpt: 'How to structure a B2B SaaS Google Ads account from scratch: segment campaigns by intent and funnel stage, isolate brand and competitor traffic, name for scale, and add Performance Max only after Search has a feedback loop. Full blueprint with example layout.', category: 'b2b', author: 'By Kampaio Team', date: '2026-06-16', readTime: '11 min read', slug: 'b2b-saas-google-ads-campaign-structure' },
  { id: 41, title: 'Is Google Ads Worth It for B2B SaaS? A Decision Framework (2026)', excerpt: 'Is Google Ads worth it for your B2B SaaS, or a money-pit? An honest decision framework: a 6-factor scorecard, the real CPL-to-CAC economics, the alternatives, and a cheap 4-6 week test to de-risk the commitment.', category: 'b2b', author: 'By Kampaio Team', date: '2026-06-16', readTime: '11 min read', slug: 'is-google-ads-worth-it-for-b2b-saas' },
  { id: 40, title: 'Google Ads Invalid Traffic & Click Fraud: How to Spot It, Stop It, and Get Refunded (2026)', excerpt: 'Suspicious clicks draining your Google Ads budget? Learn how to tell real click fraud from invalid traffic, diagnose it in 5 minutes, claim Google\'s automatic credits, and lock it down with IP and audience exclusions.', category: 'google-ads', author: 'By Kampaio Team', date: '2026-06-15', readTime: '11 min read', slug: 'google-ads-invalid-traffic-click-fraud' },
  { id: 39, title: 'How to Switch Google Ads Agencies Without Losing Your Account or Your Data', excerpt: 'A step-by-step guide to switching Google Ads agencies safely: who owns the account, how to transfer the MCC and billing, export your history, and avoid the agency that will not hand over access.', category: 'ppc', author: 'By Kampaio Team', date: '2026-06-14', readTime: '10 min read', slug: 'how-to-switch-google-ads-agencies' },
  { id: 38, title: 'Google Ads Negative Keywords: A Repeatable Method to Cut Wasted Spend (2026)', excerpt: 'Stop wasting budget on irrelevant clicks. A repeatable weekly method for Google Ads negative keywords: find them in the search terms report, pick the right match type and level, handle Performance Max, and avoid over-blocking.', category: 'google-ads', author: 'By Kampaio Team', date: '2026-06-13', readTime: '10 min read', slug: 'google-ads-negative-keywords' },
  { id: 37, title: 'How Much Does PPC Management Cost? A Real Breakdown for DTC Owners (2026)', excerpt: 'PPC management costs $500 to $10,000 a month, or 10 to 20% of ad spend. The three pricing models decoded, the honest line-item breakdown, and the math on whether the fee is worth it at your spend.', category: 'ppc', author: 'By Kampaio Team', date: '2026-06-11', readTime: '9 min read', slug: 'ppc-management-cost' },
  { id: 36, title: "How to Choose a PPC Agency (and How to Know When You Don't Need One)", excerpt: "A buyer's framework for choosing a PPC agency: fair fees, red flags, the questions to ask, and an honest test for whether you even need an agency or just better tooling.", category: 'strategy', author: 'By Kampaio Team', date: '2026-06-10', readTime: '11 min read', slug: 'how-to-choose-a-ppc-agency' },
  { id: 35, title: 'Google Ads Smart Bidding Strategies: How to Choose the Right One (and When to Avoid Each)', excerpt: 'A decision guide to all six Google Ads Smart Bidding strategies: when to use Target CPA vs Target ROAS vs Maximize Conversions, the data thresholds each needs, and when to avoid automation entirely.', category: 'google-ads', author: 'By Kampaio Team', date: '2026-06-08', readTime: '11 min read', slug: 'google-ads-smart-bidding-strategies' },
  { id: 34, title: "Google Ads for B2B SaaS: The Complete Operator's Playbook (2026)", excerpt: 'A complete operator playbook for running Google Ads for B2B SaaS: thin category volume, long sales cycles, buying committees, and attribution. Setup, 4-tier campaign structure, bidding progression, measurement, and scaling.', category: 'b2b', author: 'By Kampaio Team', date: '2026-06-07', readTime: '13 min read', slug: 'google-ads-for-b2b-saas' },
  { id: 33, title: "Google Ads Strategy: A Strategic Operator's Framework (2026)", excerpt: 'Most Google Ads advice is tactics. This pillar covers the strategy layer: a stack of six decisions (objective, structure, budget, bidding, measurement, organization) and how the stack shifts as spend scales from $10K to $100K per month.', category: 'strategy', author: 'By B6 Team', date: '2026-06-06', readTime: '13 min read', slug: 'google-ads-strategy' },
  { id: 32, title: 'How to Improve Lead Quality in Google Ads (Complete 2026 Guide)', excerpt: 'Google Ads sending leads that sales rejects? This guide covers what a qualified lead is, how to measure the gap, why quality drops, and the six levers that fix it.', category: 'b2b', author: 'By B6 Team', date: '2026-06-05', readTime: '13 min read', slug: 'google-ads-lead-quality-guide' },
  { id: 31, title: 'PPC Management: How In-House Teams Actually Run Paid Search (2026 Guide)', excerpt: 'What PPC management really is and how an in-house team runs it: the six core disciplines, a weekly and monthly operating cadence, when to audit or restructure, and how to decide if you still need an agency.', category: 'ppc', author: 'By B6 Team', date: '2026-06-04', readTime: '13 min read', slug: 'ppc-management' },
  { id: 30, title: 'How to Scale Google Ads Without Losing ROAS (2026 Playbook)', excerpt: 'Scaling Google Ads spend without tanking ROAS comes down to one rule: raise budgets 20% at a time, wait for Smart Bidding to re-stabilize, and expand demand instead of buying more of the same clicks.', category: 'strategy', author: 'By B6 Team', date: '2026-06-03', readTime: '11 min read', slug: 'how-to-scale-google-ads-without-losing-roas' },
  { id: 280, title: "Why Isn't My Brand Showing Up in ChatGPT? (How to Diagnose It)", excerpt: 'Your brand ranks on Google but never appears in ChatGPT answers? Here are the real root causes and a step-by-step way to diagnose which one is yours.', category: 'ai-search', author: 'By B6 Team', date: '2026-06-02', readTime: '9 min read', slug: 'why-brand-not-showing-up-in-chatgpt' },
  { id: 1, title: 'What CEOs Want to See in Google Ads Reports', excerpt: "Learn which Google Ads metrics CEOs care about (hint: it's not clicks) and get the exact reporting template that secures bigger budgets.", category: 'strategy', author: 'By B6 Team', date: '2025-07-15', readTime: '12 min read', featured: true, slug: 'what-ceos-want-google-ads-reports' },
  { id: 2, title: '10 AI-Powered PPC Optimization Strategies That Actually Work', excerpt: 'Discover how artificial intelligence is revolutionizing PPC campaigns and learn proven strategies to boost your ROI.', category: 'ai', author: 'By B6 Team', date: '2025-07-14', readTime: '8 min read', slug: '10-ai-powered-ppc-optimization-strategies' },
  { id: 3, title: 'The Complete Guide to Google Ads Quality Score in 2026', excerpt: 'Master the fundamentals of Quality Score and learn advanced techniques to improve your ad performance in 2026.', category: 'google-ads', author: 'By B6 Team', date: '2026-05-15', readTime: '12 min read', slug: 'the-complete-guide-to-google-ads-quality-score-in-2025' },
  { id: 4, title: '5 Tips for Working with AI-Powered PPC Tools', excerpt: "While competitors struggle with AI, you'll master it. Discover prompts and workflows top PPC pros use to 10x your productivity.", category: 'ai', author: 'By B6 Team', date: '2025-07-22', readTime: '7 min read', slug: '5-tips-for-working-with-ai-ppc-tools' },
  { id: 6, title: 'Why Performance Max Fails in B2B Marketing', excerpt: "The dirty secret Google won't tell you: Performance Max is built for B2C, not B2B. Learn why it fails and get the alternative strategy that actually works.", category: 'google-ads', author: 'By B6 Team', date: '2025-07-23', readTime: '9 min read', slug: 'performance-max-problems-b2b-marketing' },
  { id: 7, title: 'How AI is Transforming Google Ads in 2025', excerpt: "It's 2025, AI is already transforming Google Ads. Discover the new rules of PPC and get instant, personalized insights to boost your campaigns today.", category: 'ai', author: 'By B6 Team', date: '2025-07-24', readTime: '10 min read', slug: 'how-ai-is-transforming-google-ads-in-2025' },
  { id: 8, title: 'Performance Max Not Converting? 9 Fixes That Actually Work (2026 Playbook)', excerpt: 'Performance Max burning budget without conversions? 9 diagnostic steps from conversion tracking to bid strategy to landing pages, with thresholds and timelines.', category: 'google-ads', author: 'By B6 Team', date: '2026-05-12', readTime: '10 min read', slug: 'performance-max-not-converting' },
  { id: 9, title: 'Google Ads ROAS Dropped Suddenly? 8 Diagnostic Steps That Find the Real Cause (2026 Playbook)', excerpt: 'Google Ads ROAS dropped overnight? Most "ROAS drops" are tracking problems in disguise. An 8-step diagnostic checklist with thresholds and timelines for SMB owners.', category: 'google-ads', author: 'By B6 Team', date: '2026-05-12', readTime: '10 min read', slug: 'google-ads-roas-dropped-suddenly' },
  { id: 10, title: "Google Ads Without an Agency: When DIY Works, When It Doesn't, and the Third Option", excerpt: 'Can you manage Google Ads without paying an agency $2K/month? Yes, if your spend is under $20K and you use the right tools. Here is a realistic framework for SMB owners.', category: 'strategy', author: 'By B6 Team', date: '2026-05-13', readTime: '12 min read', slug: 'google-ads-without-agency' },
  { id: 11, title: 'Google Ads Not Spending Full Budget? 7 Causes and How to Fix Each One', excerpt: 'Your Google Ads campaign is not spending its daily budget. Here are the 7 most common causes, how to diagnose each one in under 2 minutes, and step-by-step fixes.', category: 'google-ads', author: 'By B6 Team', date: '2026-05-14', readTime: '11 min read', slug: 'google-ads-not-spending-full-budget' },
  { id: 12, title: "8 Signs It's Time to Fire Your PPC Agency (And What to Do Next)", excerpt: 'Eight observable signs your PPC agency is failing, a self-scoring diagnostic, and a step-by-step plan for what to do next: confront, switch, or go independent with AI tools.', category: 'strategy', author: 'By B6 Team', date: '2026-05-14', readTime: '12 min read', slug: 'signs-you-need-to-fire-your-ppc-agency' },
  { id: 13, title: 'Google Ads Conversion Tracking Not Working? The 90-Second Triage and 7 Fixes That Actually Work', excerpt: 'Run this 90-second triage first, then fix the 7 most common failure modes: tag missing, duplicate conversions, GA4 mismatch, gclid stripped, enhanced conversions silent fail.', category: 'google-ads', author: 'By B6 Team', date: '2026-05-14', readTime: '11 min read', slug: 'google-ads-conversion-tracking-not-working' },
  { id: 14, title: 'Google Ads Cost Per Click Too High: 9 Reasons + the Fix Sheet for Each', excerpt: 'Your CPC is high for one of 9 specific causes. Diagnostic triage, per-cause fix, and the real numbers we cut CPC by on live accounts (including a 23% CPC drop in 14 days, no bid changes).', category: 'google-ads', author: 'By B6 Team', date: '2026-05-15', readTime: '13 min read', slug: 'google-ads-cost-per-click-too-high' },
  { id: 15, title: 'Google Ads Anomaly Detection: Spend Spikes, Conversion Drops, Tracking Outages', excerpt: 'Built-in Google Ads alerts are too noisy or too late. The Account Anomaly Detector script is brittle. The detection stack that actually works in 2026: rolling baselines, severity tiers, and Aegis classification.', category: 'google-ads', author: 'By B6 Team', date: '2026-05-15', readTime: '12 min read', slug: 'google-ads-anomaly-detection' },
  { id: 16, title: 'Responsive Search Ads Best Practices for Senior PPC Managers (2026)', excerpt: 'Technical RSA best practices: ML signal quality, asset combinations, ad strength forensics, pinning trade-offs, variant testing with statistical significance.', category: 'google-ads', author: 'By B6 Team', date: '2026-05-15', readTime: '13 min read', slug: 'responsive-search-ads-best-practices' },
  { id: 17, title: 'Incrementality Testing in Google Ads: What It Measures, How to Run One, and Why Smart Bidding Needs It', excerpt: 'Smart Bidding optimizes against last-touch conversions. Lift testing measures causal conversions. Covers Conversion Lift, geo experiments, the Nov 2025 $5K minimum, design pitfalls, and the Smart Bidding feedback loop.', category: 'google-ads', author: 'By B6 Team', date: '2026-05-18', readTime: '13 min read', slug: 'incrementality-testing-google-ads' },
  { id: 18, title: 'AI-Powered PPC Optimization: The Complete Guide for Senior PPC Managers', excerpt: 'A senior PPC manager pillar on AI-PPC. What AI actually decides at the auction-signal level, recommendation vs autonomous tools, a calibrated adoption roadmap, realistic 12-25% ROAS lift on 90 days, and where senior judgment still wins.', category: 'google-ads', author: 'By B6 Team', date: '2026-05-18', readTime: '14 min read', slug: 'ai-powered-ppc-optimization-complete-guide' },
  { id: 19, title: 'Why Google Ads Strategy Fails at Scale: 8 Diagnostic Patterns Agencies See', excerpt: 'Across 20+ client accounts an agency owner sees the same 8 patterns when Google Ads strategy stalls at scale: auction signal exhaustion, attribution drift, KPI misalignment, vendor sprawl. The diagnostic framework to find which is killing your account.', category: 'strategy', author: 'By B6 Team', date: '2026-05-18', readTime: '13 min read', slug: 'why-google-ads-strategy-fails-at-scale' },
  { id: 20, title: 'Google Ads Attribution Models: A 2026 Guide to Picking the Right One (and Why It Affects Smart Bidding)', excerpt: "A senior PPC manager's guide to Google Ads attribution models in 2026. Why Google deprecated four of them, when data-driven beats last-click, the 300-conversion DDA threshold, the Model Comparison tool, and how the attribution choice trains Smart Bidding.", category: 'google-ads', author: 'By B6 Team', date: '2026-05-19', readTime: '14 min read', slug: 'google-ads-attribution-models-guide' },
  { id: 21, title: 'Google Ads Keyword Match Types Explained (Broad, Phrase, Exact 2026)', excerpt: 'Broad, phrase, and exact match in Google Ads behave nothing like they did in 2019. How each one works in 2026, how they feed Smart Bidding, and the decision rule that covers 80% of accounts we audit.', category: 'google-ads', author: 'By B6 Team', date: '2026-05-20', readTime: '13 min read', slug: 'google-ads-keyword-match-types-explained' },
  { id: 22, title: 'PPC Audit Checklist: 25 Senior-Level Checks That Surface 80% of Account Problems (2026)', excerpt: 'A senior PPC audit checklist organized in 6 pillars with thresholds, a 3x3 decision matrix, and the 18 checks you can automate. Built for agency owners auditing 4+ accounts a quarter.', category: 'ppc', author: 'By B6 Team', date: '2026-05-21', readTime: '11 min read', slug: 'ppc-audit-checklist' },
  { id: 23, title: 'Google Ads "Bid Strategy Limited" Status: What It Means and How to Fix It', excerpt: 'What "Limited by bid strategy" and "Eligible (Limited)" mean, the four real causes, the 5-step fix, and when ignoring the warning is the right call.', category: 'google-ads', author: 'By B6 Team', date: '2026-05-22', readTime: '12 min read', slug: 'google-ads-bid-strategy-status-limited' },
  { id: 24, title: 'Google Ads Display Network Wasted Spend: How to Stop the Bleeding (2026 Guide)', excerpt: 'Display Network silently drains 20-60% of Google Ads budgets on low-intent traffic. The 60-second fix, a 5-minute audit, and the smaller settings (Display Expansion, Search Partners) that keep leaking.', category: 'ppc', author: 'By B6 Team', date: '2026-05-26', readTime: '9 min read', slug: 'google-ads-display-network-wasted-spend' },
  { id: 25, title: 'Google Ads Account Restructure: The 4-Phase Playbook (2026)', excerpt: 'When and how to restructure a messy Google Ads account: the 3-campaign rule, 4-phase rollout over 8 weeks, what to migrate vs what to leave alone, and the thresholds that signal it is time.', category: 'ppc', author: 'By B6 Team', date: '2026-05-27', readTime: '10 min read', slug: 'google-ads-account-restructure' },
  { id: 26, title: 'How to Fix Low-Quality Leads From B2B Google Ads (2026 Playbook)', excerpt: 'B2B form fills look fine but pipeline does not move? The six-step fix sequence: offline conversion imports, value-based bidding, audience exclusions, form filtering, match types, lead form match-quality score.', category: 'google-ads', author: 'By B6 Team', date: '2026-05-28', readTime: '11 min read', slug: 'b2b-google-ads-low-quality-leads' },
  { id: 27, title: 'LinkedIn Ads vs Google Ads for B2B Lead Generation: Honest 2026 Comparison', excerpt: 'LinkedIn delivers 121% ROAS for B2B in 2026, Google Search 67% (Dreamdata). But CPL, intent type, and lead quality tell a more complex story. Honest comparison across 8 axes with budget split frameworks for $20-100K/mo B2B advertisers.', category: 'b2b', author: 'By Kampaio Team', date: '2026-05-29', readTime: '15 min read', slug: 'linkedin-ads-vs-google-ads-b2b-lead-generation' },
  { id: 290, title: 'B2B Google Ads Lead Generation: How to Build a Campaign That Feeds the Pipeline', excerpt: 'B2B Google Ads requires a different structure than B2C. Here is how to set up campaigns, conversion tracking, and bidding for long sales cycles that actually produce qualified pipeline.', category: 'b2b', author: 'By B6 Team', date: '2026-05-28', readTime: '13 min read', slug: 'b2b-google-ads-lead-generation' },
  { id: 291, title: 'B2B SaaS Google Ads Benchmarks 2026: CTR, CPC, CPA, and ROAS by Segment', excerpt: 'B2B SaaS Google Ads benchmarks for 2026: average CPC $5.34 (up 29% YoY), CPA $87-$1,500+ by segment, conversion rate 3-5%. Real data from 2,000+ SaaS campaigns to tell you if your numbers are on target.', category: 'b2b', author: 'By B6 Team', date: '2026-06-01', readTime: '16 min read', slug: 'b2b-saas-google-ads-benchmarks-2026' },
];

const byDateDesc = (a: BlogPost, b: BlogPost) =>
  new Date(b.date).getTime() - new Date(a.date).getTime();

export function sortedPosts(): BlogPost[] {
  return [...blogPosts].sort(byDateDesc);
}

export function postBySlug(slug: string): BlogPost | undefined {
  return blogPosts.find((p) => p.slug === slug);
}

// Recirculation for the "Keep reading" block: same-category articles first
// (excluding the current one), then filled with the most recent others.
export function relatedPosts(slug: string, category: string, n = 3): BlogPost[] {
  const sameCat = blogPosts
    .filter((p) => p.category === category && p.slug !== slug)
    .sort(byDateDesc);
  if (sameCat.length >= n) return sameCat.slice(0, n);
  const seen = new Set([slug, ...sameCat.map((p) => p.slug)]);
  const recent = sortedPosts().filter((p) => !seen.has(p.slug));
  return [...sameCat, ...recent].slice(0, n);
}
