services:
  - type: web
    name: ppcset-ai-server
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: OPENAI_API_KEY
        sync: false
      - key: AI_SERVER_HOST
        value: 0.0.0.0
      - key: AI_SERVER_PORT
        value: $PORT
      - key: AI_SERVER_RELOAD
        value: false 