'use client';

/**
 * InlineSVG — renders a raw SVG string inside blog articles.
 *
 * For custom illustrations and data charts that the LLM writes directly as
 * SVG code. The component wraps the SVG in a styled <figure> with optional
 * caption so it integrates with the article aesthetic.
 *
 * Common uses:
 *   - Custom data charts (LLM-generated SVG with real numbers from the article)
 *   - Brand-colored icons or illustrations
 *   - Annotated mock screenshots (SVG overlays)
 *
 * Example usage:
 *
 *   <InlineSVG
 *     svg={`<svg viewBox="0 0 400 200" xmlns="http://www.w3.org/2000/svg">
 *       <rect x="10" y="50" width="60" height="100" fill="#667eea" />
 *       <text x="40" y="180" text-anchor="middle">Buzz</text>
 *     </svg>`}
 *     caption="Buzz reduces CPC by 12% on average"
 *     ariaLabel="Bar chart showing Buzz performance"
 *   />
 *
 * Security: SVG is rendered via dangerouslySetInnerHTML. Only inject SVG
 * generated by the LLM pipeline (publisher.md), never user-controlled input.
 */

interface InlineSVGProps {
  svg: string;
  caption?: string;
  ariaLabel?: string;
  maxWidth?: number;
}

export default function InlineSVG({ svg, caption, ariaLabel, maxWidth = 700 }: InlineSVGProps) {
  return (
    <figure
      style={{
        margin: '32px auto',
        maxWidth: `${maxWidth}px`,
        padding: '24px',
        background: '#f8fafc',
        border: '1px solid #e2e8f0',
        borderRadius: '12px',
      }}
      role="img"
      aria-label={ariaLabel || caption || 'Inline illustration'}
    >
      <div
        style={{ display: 'flex', justifyContent: 'center' }}
        dangerouslySetInnerHTML={{ __html: svg }}
      />
      {caption && (
        <figcaption
          style={{
            marginTop: '12px',
            fontSize: '14px',
            color: '#64748b',
            textAlign: 'center',
            fontStyle: 'italic',
          }}
        >
          {caption}
        </figcaption>
      )}
    </figure>
  );
}
