"""initial b6 schema

Revision ID: 84cf759d7c69
Revises: 
Create Date: 2026-05-12 00:47:07.847087

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '84cf759d7c69'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('stripe_customer_id', sa.String(length=255), nullable=True),
    sa.Column('subscription_tier', sa.String(length=50), nullable=True),
    sa.Column('autonomy_level', sa.String(length=10), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_email'), ['email'], unique=True)

    op.create_table('agents',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('type', sa.String(length=50), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('mascot_name', sa.String(length=50), nullable=True),
    sa.Column('config', sa.JSON(), nullable=True),
    sa.Column('last_run_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('agents', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_agents_user_id'), ['user_id'], unique=False)

    op.create_table('google_ads_accounts',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('google_customer_id', sa.String(length=50), nullable=False),
    sa.Column('oauth_refresh_token', sa.Text(), nullable=False),
    sa.Column('timezone', sa.String(length=50), nullable=True),
    sa.Column('currency', sa.String(length=10), nullable=True),
    sa.Column('connected_at', sa.DateTime(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('google_ads_accounts', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_google_ads_accounts_user_id'), ['user_id'], unique=False)

    op.create_table('safety_caps',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('cap_type', sa.String(length=50), nullable=False),
    sa.Column('limit_value', sa.Numeric(), nullable=False),
    sa.Column('current_value', sa.Numeric(), nullable=False),
    sa.Column('reset_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'cap_type', name='uq_user_captype')
    )
    with op.batch_alter_table('safety_caps', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_safety_caps_user_id'), ['user_id'], unique=False)

    op.create_table('activity_events',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('agent_id', sa.String(length=36), nullable=True),
    sa.Column('event_type', sa.String(length=50), nullable=False),
    sa.Column('payload', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['agent_id'], ['agents.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('activity_events', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_activity_events_user_id'), ['user_id'], unique=False)
        batch_op.create_index('ix_activity_user_created', ['user_id', 'created_at'], unique=False)

    op.create_table('agent_actions',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('agent_id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('action_type', sa.String(length=50), nullable=False),
    sa.Column('target', sa.JSON(), nullable=True),
    sa.Column('before_state', sa.JSON(), nullable=True),
    sa.Column('after_state', sa.JSON(), nullable=True),
    sa.Column('reasoning', sa.Text(), nullable=True),
    sa.Column('confidence', sa.Numeric(precision=3, scale=2), nullable=True),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('approved_by', sa.String(length=36), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('applied_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['agent_id'], ['agents.id'], ),
    sa.ForeignKeyConstraint(['approved_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('agent_actions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_agent_actions_agent_id'), ['agent_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_agent_actions_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_agent_actions_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_agent_actions_user_id'), ['user_id'], unique=False)

    op.create_table('audit_log',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('action_id', sa.String(length=36), nullable=True),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('event_type', sa.String(length=50), nullable=False),
    sa.Column('payload', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['action_id'], ['agent_actions.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('audit_log', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_audit_log_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_audit_log_user_id'), ['user_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('audit_log', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_audit_log_user_id'))
        batch_op.drop_index(batch_op.f('ix_audit_log_created_at'))

    op.drop_table('audit_log')
    with op.batch_alter_table('agent_actions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_agent_actions_user_id'))
        batch_op.drop_index(batch_op.f('ix_agent_actions_status'))
        batch_op.drop_index(batch_op.f('ix_agent_actions_created_at'))
        batch_op.drop_index(batch_op.f('ix_agent_actions_agent_id'))

    op.drop_table('agent_actions')
    with op.batch_alter_table('activity_events', schema=None) as batch_op:
        batch_op.drop_index('ix_activity_user_created')
        batch_op.drop_index(batch_op.f('ix_activity_events_user_id'))

    op.drop_table('activity_events')
    with op.batch_alter_table('safety_caps', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_safety_caps_user_id'))

    op.drop_table('safety_caps')
    with op.batch_alter_table('google_ads_accounts', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_google_ads_accounts_user_id'))

    op.drop_table('google_ads_accounts')
    with op.batch_alter_table('agents', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_agents_user_id'))

    op.drop_table('agents')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_email'))

    op.drop_table('users')
    # ### end Alembic commands ###
