"""Generate a client-facing PDF from an Echo digest payload.

The digest payload comes from `agents/reporting_agent.py::EchoAgent` —
{summary_text, actions_count, applied, rejected, blocks, top_decisions[],
advice, period, generated_at}.

We render it as a simple branded single-page report. Kept dependency-light
(reportlab only — already in requirements.txt). No external fonts, no images
in v1 — easy to extend later.
"""
from __future__ import annotations

from io import BytesIO
from typing import Any, Optional

from reportlab.lib import colors
from reportlab.lib.pagesizes import A4
from reportlab.lib.styles import ParagraphStyle, getSampleStyleSheet
from reportlab.lib.units import mm
from reportlab.platypus import (
    Paragraph,
    SimpleDocTemplate,
    Spacer,
    Table,
    TableStyle,
)


B6_BRAND_COLOR = colors.HexColor("#00BFAE")
B6_DARK = colors.HexColor("#15181D")
B6_GREY = colors.HexColor("#A0A0A0")
B6_LIGHT_BG = colors.HexColor("#F4F6F8")


def build_digest_pdf(digest: dict[str, Any], *, customer_label: Optional[str] = None) -> bytes:
    """Return PDF bytes for a single-page client report."""
    buf = BytesIO()
    doc = SimpleDocTemplate(
        buf,
        pagesize=A4,
        topMargin=18 * mm,
        bottomMargin=18 * mm,
        leftMargin=18 * mm,
        rightMargin=18 * mm,
        title=f"Weekly report · {customer_label or 'Google Ads'}",
        author="B6 — Autonomous PPC Cabinet",
    )

    styles = getSampleStyleSheet()
    h_brand = ParagraphStyle(
        "BrandHeader",
        parent=styles["Title"],
        fontName="Helvetica-Bold",
        fontSize=20,
        textColor=B6_DARK,
        spaceAfter=2,
        leading=24,
    )
    h_sub = ParagraphStyle(
        "BrandSubheader",
        parent=styles["Normal"],
        fontName="Helvetica",
        fontSize=10,
        textColor=B6_GREY,
        spaceAfter=14,
    )
    h_section = ParagraphStyle(
        "Section",
        parent=styles["Heading2"],
        fontName="Helvetica-Bold",
        fontSize=12,
        textColor=B6_BRAND_COLOR,
        spaceBefore=12,
        spaceAfter=6,
    )
    body = ParagraphStyle(
        "Body",
        parent=styles["Normal"],
        fontName="Helvetica",
        fontSize=10.5,
        leading=14,
        textColor=B6_DARK,
        spaceAfter=6,
    )
    bullet = ParagraphStyle(
        "Bullet",
        parent=body,
        leftIndent=12,
        bulletIndent=2,
        spaceAfter=3,
    )
    footer = ParagraphStyle(
        "Footer",
        parent=styles["Normal"],
        fontName="Helvetica-Oblique",
        fontSize=8,
        textColor=B6_GREY,
        alignment=1,  # center
    )

    flow: list = []

    # Header
    flow.append(Paragraph("Weekly Google Ads Report", h_brand))
    sub = "Generated by B6 · Autonomous PPC Cabinet"
    if customer_label:
        sub = f"{customer_label} · {digest.get('period', '')} · {sub}"
    else:
        sub = f"{digest.get('period', '')} · {sub}"
    flow.append(Paragraph(sub, h_sub))

    # Stat strip (4 numbers)
    stats = [
        ("Actions", digest.get("actions_count", 0)),
        ("Applied", digest.get("applied", 0)),
        ("Held for review", digest.get("rejected", 0) + digest.get("blocks", 0)),
        ("Risk blocks", digest.get("blocks", 0)),
    ]
    stat_data = [[
        Paragraph(f"<b><font color='{B6_BRAND_COLOR.hexval()}' size='14'>{v}</font></b><br/>"
                  f"<font color='{B6_GREY.hexval()}' size='8'>{label.upper()}</font>", body)
        for label, v in stats
    ]]
    stat_table = Table(stat_data, colWidths=[40 * mm] * 4)
    stat_table.setStyle(TableStyle([
        ("BACKGROUND", (0, 0), (-1, -1), B6_LIGHT_BG),
        ("VALIGN", (0, 0), (-1, -1), "MIDDLE"),
        ("ALIGN", (0, 0), (-1, -1), "CENTER"),
        ("LEFTPADDING", (0, 0), (-1, -1), 10),
        ("RIGHTPADDING", (0, 0), (-1, -1), 10),
        ("TOPPADDING", (0, 0), (-1, -1), 12),
        ("BOTTOMPADDING", (0, 0), (-1, -1), 12),
        ("LINEBELOW", (0, 0), (-1, -1), 0.25, colors.lightgrey),
    ]))
    flow.append(stat_table)
    flow.append(Spacer(1, 4 * mm))

    # Summary
    summary = (digest.get("summary_text") or "").strip()
    if summary:
        flow.append(Paragraph("Headline", h_section))
        flow.append(Paragraph(summary, body))

    # Top decisions (bulleted)
    decisions = digest.get("top_decisions") or []
    if decisions:
        flow.append(Paragraph("What we did", h_section))
        for d in decisions:
            emoji = d.get("emoji", "•")
            agent = d.get("agent", "")
            when = d.get("when") or ""
            text = d.get("summary") or ""
            line = f"<b>{emoji} {agent}</b>"
            if when:
                line += f" <font color='{B6_GREY.hexval()}'>· {when}</font>"
            line += f"<br/>{text}"
            flow.append(Paragraph(line, bullet))

    # Advice
    advice = (digest.get("advice") or "").strip()
    if advice:
        flow.append(Paragraph("Recommendation for next week", h_section))
        flow.append(Paragraph(advice, body))

    flow.append(Spacer(1, 8 * mm))
    flow.append(Paragraph(
        "This report is automatically generated by B6. Reach out to your account "
        "manager for questions or to adjust the level of automation.",
        footer,
    ))

    doc.build(flow)
    pdf_bytes = buf.getvalue()
    buf.close()
    return pdf_bytes
